// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datum.proto

package com.adobe.datum.common.api;

public final class DatumProto {
  private DatumProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DatumRequestProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .datum.api.DatumRequestProto.RequestType type = 1;
    /**
     * <code>required .datum.api.DatumRequestProto.RequestType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .datum.api.DatumRequestProto.RequestType type = 1;</code>
     */
    com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType getType();

    // required string parameter_type = 2;
    /**
     * <code>required string parameter_type = 2;</code>
     */
    boolean hasParameterType();
    /**
     * <code>required string parameter_type = 2;</code>
     */
    java.lang.String getParameterType();
    /**
     * <code>required string parameter_type = 2;</code>
     */
    com.google.protobuf.ByteString
        getParameterTypeBytes();

    // required bytes parameter_body = 3;
    /**
     * <code>required bytes parameter_body = 3;</code>
     */
    boolean hasParameterBody();
    /**
     * <code>required bytes parameter_body = 3;</code>
     */
    com.google.protobuf.ByteString getParameterBody();

    // required string prototype_name = 4;
    /**
     * <code>required string prototype_name = 4;</code>
     */
    boolean hasPrototypeName();
    /**
     * <code>required string prototype_name = 4;</code>
     */
    java.lang.String getPrototypeName();
    /**
     * <code>required string prototype_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getPrototypeNameBytes();
  }
  /**
   * Protobuf type {@code datum.api.DatumRequestProto}
   */
  public static final class DatumRequestProto extends
      com.google.protobuf.GeneratedMessage
      implements DatumRequestProtoOrBuilder {
    // Use DatumRequestProto.newBuilder() to construct.
    private DatumRequestProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DatumRequestProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DatumRequestProto defaultInstance;
    public static DatumRequestProto getDefaultInstance() {
      return defaultInstance;
    }

    public DatumRequestProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DatumRequestProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType value = com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              parameterType_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              parameterBody_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              prototypeName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.adobe.datum.common.api.DatumProto.internal_static_datum_api_DatumRequestProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.adobe.datum.common.api.DatumProto.internal_static_datum_api_DatumRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.adobe.datum.common.api.DatumProto.DatumRequestProto.class, com.adobe.datum.common.api.DatumProto.DatumRequestProto.Builder.class);
    }

    public static com.google.protobuf.Parser<DatumRequestProto> PARSER =
        new com.google.protobuf.AbstractParser<DatumRequestProto>() {
      public DatumRequestProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DatumRequestProto(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DatumRequestProto> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code datum.api.DatumRequestProto.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DOWNLOAD = 0;</code>
       */
      DOWNLOAD(0, 0),
      /**
       * <code>UPLOAD = 1;</code>
       */
      UPLOAD(1, 1),
      ;

      /**
       * <code>DOWNLOAD = 0;</code>
       */
      public static final int DOWNLOAD_VALUE = 0;
      /**
       * <code>UPLOAD = 1;</code>
       */
      public static final int UPLOAD_VALUE = 1;


      public final int getNumber() { return value; }

      public static RequestType valueOf(int value) {
        switch (value) {
          case 0: return DOWNLOAD;
          case 1: return UPLOAD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.adobe.datum.common.api.DatumProto.DatumRequestProto.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private RequestType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:datum.api.DatumRequestProto.RequestType)
    }

    private int bitField0_;
    // required .datum.api.DatumRequestProto.RequestType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType type_;
    /**
     * <code>required .datum.api.DatumRequestProto.RequestType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .datum.api.DatumRequestProto.RequestType type = 1;</code>
     */
    public com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType getType() {
      return type_;
    }

    // required string parameter_type = 2;
    public static final int PARAMETER_TYPE_FIELD_NUMBER = 2;
    private java.lang.Object parameterType_;
    /**
     * <code>required string parameter_type = 2;</code>
     */
    public boolean hasParameterType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string parameter_type = 2;</code>
     */
    public java.lang.String getParameterType() {
      java.lang.Object ref = parameterType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          parameterType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string parameter_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParameterTypeBytes() {
      java.lang.Object ref = parameterType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parameterType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bytes parameter_body = 3;
    public static final int PARAMETER_BODY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString parameterBody_;
    /**
     * <code>required bytes parameter_body = 3;</code>
     */
    public boolean hasParameterBody() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes parameter_body = 3;</code>
     */
    public com.google.protobuf.ByteString getParameterBody() {
      return parameterBody_;
    }

    // required string prototype_name = 4;
    public static final int PROTOTYPE_NAME_FIELD_NUMBER = 4;
    private java.lang.Object prototypeName_;
    /**
     * <code>required string prototype_name = 4;</code>
     */
    public boolean hasPrototypeName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string prototype_name = 4;</code>
     */
    public java.lang.String getPrototypeName() {
      java.lang.Object ref = prototypeName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          prototypeName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string prototype_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPrototypeNameBytes() {
      java.lang.Object ref = prototypeName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prototypeName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      type_ = com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType.DOWNLOAD;
      parameterType_ = "";
      parameterBody_ = com.google.protobuf.ByteString.EMPTY;
      prototypeName_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParameterType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasParameterBody()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrototypeName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getParameterTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, parameterBody_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPrototypeNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getParameterTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, parameterBody_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPrototypeNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.adobe.datum.common.api.DatumProto.DatumRequestProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adobe.datum.common.api.DatumProto.DatumRequestProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adobe.datum.common.api.DatumProto.DatumRequestProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.adobe.datum.common.api.DatumProto.DatumRequestProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.adobe.datum.common.api.DatumProto.DatumRequestProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.adobe.datum.common.api.DatumProto.DatumRequestProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.adobe.datum.common.api.DatumProto.DatumRequestProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.adobe.datum.common.api.DatumProto.DatumRequestProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.adobe.datum.common.api.DatumProto.DatumRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.adobe.datum.common.api.DatumProto.DatumRequestProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.adobe.datum.common.api.DatumProto.DatumRequestProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code datum.api.DatumRequestProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.adobe.datum.common.api.DatumProto.DatumRequestProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.adobe.datum.common.api.DatumProto.internal_static_datum_api_DatumRequestProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.adobe.datum.common.api.DatumProto.internal_static_datum_api_DatumRequestProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.adobe.datum.common.api.DatumProto.DatumRequestProto.class, com.adobe.datum.common.api.DatumProto.DatumRequestProto.Builder.class);
      }

      // Construct using com.adobe.datum.common.api.DatumProto.DatumRequestProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType.DOWNLOAD;
        bitField0_ = (bitField0_ & ~0x00000001);
        parameterType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        parameterBody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        prototypeName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.adobe.datum.common.api.DatumProto.internal_static_datum_api_DatumRequestProto_descriptor;
      }

      public com.adobe.datum.common.api.DatumProto.DatumRequestProto getDefaultInstanceForType() {
        return com.adobe.datum.common.api.DatumProto.DatumRequestProto.getDefaultInstance();
      }

      public com.adobe.datum.common.api.DatumProto.DatumRequestProto build() {
        com.adobe.datum.common.api.DatumProto.DatumRequestProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.adobe.datum.common.api.DatumProto.DatumRequestProto buildPartial() {
        com.adobe.datum.common.api.DatumProto.DatumRequestProto result = new com.adobe.datum.common.api.DatumProto.DatumRequestProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.parameterType_ = parameterType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.parameterBody_ = parameterBody_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.prototypeName_ = prototypeName_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.adobe.datum.common.api.DatumProto.DatumRequestProto) {
          return mergeFrom((com.adobe.datum.common.api.DatumProto.DatumRequestProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.adobe.datum.common.api.DatumProto.DatumRequestProto other) {
        if (other == com.adobe.datum.common.api.DatumProto.DatumRequestProto.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasParameterType()) {
          bitField0_ |= 0x00000002;
          parameterType_ = other.parameterType_;
          onChanged();
        }
        if (other.hasParameterBody()) {
          setParameterBody(other.getParameterBody());
        }
        if (other.hasPrototypeName()) {
          bitField0_ |= 0x00000008;
          prototypeName_ = other.prototypeName_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasParameterType()) {
          
          return false;
        }
        if (!hasParameterBody()) {
          
          return false;
        }
        if (!hasPrototypeName()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.adobe.datum.common.api.DatumProto.DatumRequestProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.adobe.datum.common.api.DatumProto.DatumRequestProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .datum.api.DatumRequestProto.RequestType type = 1;
      private com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType type_ = com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType.DOWNLOAD;
      /**
       * <code>required .datum.api.DatumRequestProto.RequestType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .datum.api.DatumRequestProto.RequestType type = 1;</code>
       */
      public com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType getType() {
        return type_;
      }
      /**
       * <code>required .datum.api.DatumRequestProto.RequestType type = 1;</code>
       */
      public Builder setType(com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .datum.api.DatumRequestProto.RequestType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.adobe.datum.common.api.DatumProto.DatumRequestProto.RequestType.DOWNLOAD;
        onChanged();
        return this;
      }

      // required string parameter_type = 2;
      private java.lang.Object parameterType_ = "";
      /**
       * <code>required string parameter_type = 2;</code>
       */
      public boolean hasParameterType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string parameter_type = 2;</code>
       */
      public java.lang.String getParameterType() {
        java.lang.Object ref = parameterType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          parameterType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string parameter_type = 2;</code>
       */
      public com.google.protobuf.ByteString
          getParameterTypeBytes() {
        java.lang.Object ref = parameterType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parameterType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string parameter_type = 2;</code>
       */
      public Builder setParameterType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parameterType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string parameter_type = 2;</code>
       */
      public Builder clearParameterType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parameterType_ = getDefaultInstance().getParameterType();
        onChanged();
        return this;
      }
      /**
       * <code>required string parameter_type = 2;</code>
       */
      public Builder setParameterTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parameterType_ = value;
        onChanged();
        return this;
      }

      // required bytes parameter_body = 3;
      private com.google.protobuf.ByteString parameterBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes parameter_body = 3;</code>
       */
      public boolean hasParameterBody() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes parameter_body = 3;</code>
       */
      public com.google.protobuf.ByteString getParameterBody() {
        return parameterBody_;
      }
      /**
       * <code>required bytes parameter_body = 3;</code>
       */
      public Builder setParameterBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        parameterBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes parameter_body = 3;</code>
       */
      public Builder clearParameterBody() {
        bitField0_ = (bitField0_ & ~0x00000004);
        parameterBody_ = getDefaultInstance().getParameterBody();
        onChanged();
        return this;
      }

      // required string prototype_name = 4;
      private java.lang.Object prototypeName_ = "";
      /**
       * <code>required string prototype_name = 4;</code>
       */
      public boolean hasPrototypeName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string prototype_name = 4;</code>
       */
      public java.lang.String getPrototypeName() {
        java.lang.Object ref = prototypeName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          prototypeName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string prototype_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPrototypeNameBytes() {
        java.lang.Object ref = prototypeName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prototypeName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string prototype_name = 4;</code>
       */
      public Builder setPrototypeName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        prototypeName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string prototype_name = 4;</code>
       */
      public Builder clearPrototypeName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        prototypeName_ = getDefaultInstance().getPrototypeName();
        onChanged();
        return this;
      }
      /**
       * <code>required string prototype_name = 4;</code>
       */
      public Builder setPrototypeNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        prototypeName_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:datum.api.DatumRequestProto)
    }

    static {
      defaultInstance = new DatumRequestProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:datum.api.DatumRequestProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_datum_api_DatumRequestProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_datum_api_DatumRequestProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013datum.proto\022\tdatum.api\"\274\001\n\021DatumReques" +
      "tProto\0226\n\004type\030\001 \002(\0162(.datum.api.DatumRe" +
      "questProto.RequestType\022\026\n\016parameter_type" +
      "\030\002 \002(\t\022\026\n\016parameter_body\030\003 \002(\014\022\026\n\016protot" +
      "ype_name\030\004 \002(\t\"\'\n\013RequestType\022\014\n\010DOWNLOA" +
      "D\020\000\022\n\n\006UPLOAD\020\001B*\n\032com.adobe.datum.commo" +
      "n.apiB\nDatumProtoH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_datum_api_DatumRequestProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_datum_api_DatumRequestProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_datum_api_DatumRequestProto_descriptor,
              new java.lang.String[] { "Type", "ParameterType", "ParameterBody", "PrototypeName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
